apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app-deployment-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-deployment  # Nome do Deployment que será escalado
  minReplicas: 2           # Número mínimo de pods
  maxReplicas: 6          # Número máximo de pods
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 85 
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 85
