apiVersion: v1
kind: Service
metadata:
  name: processador-srv
spec:
  selector:
    app: processador-deployment
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8081
      nodePort: 31002