apiVersion: v1
kind: Service
metadata:
  name: armazenamento-srv
spec:
  selector:
    app: armazenamento-deployment
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8082
      nodePort: 31000